# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yumsa\OneDrive\문서\Sousou Project\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1112, 667)
        self.A_btn = QtWidgets.QPushButton(Form)
        self.A_btn.setGeometry(QtCore.QRect(850, 580, 111, 61))
        self.A_btn.setObjectName("A_btn")
        self.B_btn = QtWidgets.QPushButton(Form)
        self.B_btn.setGeometry(QtCore.QRect(980, 580, 111, 61))
        self.B_btn.setObjectName("B_btn")
        self.turb_display = QtWidgets.QLCDNumber(Form)
        self.turb_display.setGeometry(QtCore.QRect(850, 490, 241, 71))
        self.turb_display.setObjectName("turb_display")
        self.water_display = QtWidgets.QLCDNumber(Form)
        self.water_display.setGeometry(QtCore.QRect(850, 400, 241, 71))
        self.water_display.setObjectName("water_display")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.A_btn.setText(_translate("Form", "A"))
        self.B_btn.setText(_translate("Form", "B"))
