# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yumsa\OneDrive\문서\GitHub\graph_maker\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 571)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.big_brother = QtWidgets.QVBoxLayout()
        self.big_brother.setObjectName("big_brother")
        self.verticalLayout_2.addLayout(self.big_brother)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.water_display1 = QtWidgets.QLCDNumber(self.widget_4)
        self.water_display1.setObjectName("water_display1")
        self.verticalLayout_3.addWidget(self.water_display1)
        self.water_display2 = QtWidgets.QLCDNumber(self.widget_4)
        self.water_display2.setObjectName("water_display2")
        self.verticalLayout_3.addWidget(self.water_display2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.A_btn = QtWidgets.QPushButton(self.widget_2)
        self.A_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.A_btn.setObjectName("A_btn")
        self.horizontalLayout.addWidget(self.A_btn)
        self.b_btn = QtWidgets.QPushButton(self.widget_2)
        self.b_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.b_btn.setObjectName("b_btn")
        self.horizontalLayout.addWidget(self.b_btn)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.A_btn.setText(_translate("Form", "A"))
        self.b_btn.setText(_translate("Form", "B"))
